/**
 * `mdlineage init`: bootstrap a repository (§10.1).
 *
 * Generates the config, the `.gitattributes` line-ending policy and the empty
 * schema directory. The default is a dry run: nothing is written until
 * `--write` is passed, matching the project's "writing is explicit" decision.
 * An existing `.gitattributes` is only ever appended to, never rewritten.
 *
 * The policy line follows the config's `eolPolicy` (§4.3: "`* text=auto eol=lf`
 * (or the configured policy)"), so a repository that declared CRLF gets the
 * attribute that matches it instead of a hardcoded LF.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'node:fs';
import { cwd as processCwd } from 'node:process';
import { resolve, join } from 'node:path';
import { loadConfig, stripBom, type EolPolicy } from '@mdlineage/validator';
import { repositoryRoot } from './git.js';

const CONFIG_FILE = 'mdlineage.config.yaml';
const ATTR_FILE = '.gitattributes';
const SCHEMA_DIR = 'schemas';
const MANIFEST_FILE = 'mdlineage.manifest.yaml';

const CONFIG_CONTENT = `# MDLineage configuration (generated by \`mdlineage init\`).
configVersion: 1
# Metadata sources: out-of-band manifest (preferred) / front matter / disabled
manifestFile: mdlineage.manifest.yaml
metadata:
  # Gradual adoption: documents without metadata are warnings, not errors.
  # Set this to true once the corpus is fully onboarded.
  required: false
`;

const MANIFEST_CONTENT = `version: 1\ndocuments: {}\n`;

/**
 * The `.gitattributes` policy line for one line-ending policy (§4.3).
 *
 * git's `eol` attribute accepts `lf` and `crlf` only; a CR-only policy has no
 * attribute to express it, so the enforceable rule is the normalization alone.
 */
export function attrPolicyLine(policy: EolPolicy): string {
  if (policy === 'crlf') return '* text=auto eol=crlf';
  if (policy === 'cr') return '* text=auto';
  return '* text=auto eol=lf';
}

interface Step {
  /** Path this step writes, or null when there is nothing to do. */
  readonly target: string | null;
  /** Filesystem action to take, or null when there is nothing to do. */
  apply: (() => string) | null;
  /** One-line report of what this step does (or already did). */
  describe: string;
}

/** Plan the init steps for `root` without touching the filesystem. */
function plan(root: string, policy: string): Step[] {
  const steps: Step[] = [];

  const configPath = join(root, CONFIG_FILE);
  if (existsSync(configPath)) {
    steps.push({ target: null, apply: null, describe: `${CONFIG_FILE}: already present, left unchanged` });
  } else {
    steps.push({
      target: CONFIG_FILE,
      apply: () => {
        writeFileSync(configPath, CONFIG_CONTENT);
        return `created ${CONFIG_FILE}`;
      },
      describe: `create ${CONFIG_FILE} (manifestFile: ${MANIFEST_FILE}, metadata.required: false)`,
    });
  }

  const manifestPath = join(root, MANIFEST_FILE);
  if (existsSync(manifestPath)) {
    steps.push({ target: null, apply: null, describe: `${MANIFEST_FILE}: already present, left unchanged` });
  } else {
    steps.push({
      target: MANIFEST_FILE,
      apply: () => {
        writeFileSync(manifestPath, MANIFEST_CONTENT);
        return `created ${MANIFEST_FILE}`;
      },
      describe: `create ${MANIFEST_FILE} (empty documents manifest skeleton)`,
    });
  }

  const attrPath = join(root, ATTR_FILE);
  if (!existsSync(attrPath)) {
    steps.push({
      target: ATTR_FILE,
      apply: () => {
        writeFileSync(attrPath, `${policy}\n`);
        return `created ${ATTR_FILE}`;
      },
      describe: `create ${ATTR_FILE}:`,
    });
    steps.push({ target: null, apply: null, describe: `+${policy}` });
  } else {
    // The plan only reads this file, so an unreadable one is reported by name.
    const existing = stripBom(readFileSync(attrPath, 'utf8'));
    const lines = new Set(
      existing
        .split('\n')
        .map((line) => line.trimEnd())
        .filter((line) => line.length > 0),
    );
    if (lines.has(policy)) {
      steps.push({ target: null, apply: null, describe: `${ATTR_FILE}: already present, left unchanged` });
    } else {
      steps.push({
        target: ATTR_FILE,
        apply: () => {
          appendFileSync(attrPath, `${policy}\n`);
          return `appended to ${ATTR_FILE}`;
        },
        describe: `append to ${ATTR_FILE}:`,
      });
      steps.push({ target: null, apply: null, describe: `+${policy}` });
    }
  }

  const schemaPath = join(root, SCHEMA_DIR);
  if (existsSync(schemaPath)) {
    steps.push({ target: null, apply: null, describe: `${SCHEMA_DIR}/: already present, left unchanged` });
  } else {
    steps.push({
      target: SCHEMA_DIR,
      apply: () => {
        mkdirSync(schemaPath, { recursive: true });
        return `created ${SCHEMA_DIR}/`;
      },
      describe: `create ${SCHEMA_DIR}/ (empty schema directory)`,
    });
  }

  return steps;
}

/** `mdlineage init`: print the plan; only `--write` touches the filesystem. */
export function runInit(args: string[], values: { write?: boolean; config?: string }): number {
  const stray = args.filter((arg) => arg.startsWith('-'));
  if (stray.length > 0) {
    process.stderr.write(`mdlineage: unknown option: ${stray.join(', ')}\n\n`);
    return 2;
  }
  // `init` bootstraps the repository it runs in and takes no paths, the way
  // `check` refuses an argument it has no use for.
  const extra = args.filter((arg) => !arg.startsWith('-'));
  if (extra.length > 0) {
    process.stderr.write(`mdlineage: init takes no paths (unexpected: ${extra.join(', ')})\n\n`);
    return 2;
  }
  if (values.config) {
    process.stderr.write(`mdlineage: init does not take --config\n`);
    return 2;
  }

  const cwd = processCwd();
  // The bootstrap is a repository-level contract; fall back to the CWD when
  // there is no git repository to anchor at.
  const root = repositoryRoot(cwd) ?? resolve(cwd);
  // The config is only consulted for its line-ending policy: a repository that
  // declares one gets the attribute that matches it.
  const policy = attrPolicyLine(loadConfig(undefined, root).config.eolPolicy);

  let steps: Step[];
  try {
    steps = plan(root, policy);
  } catch (error) {
    process.stderr.write(
      `mdlineage: cannot read ${ATTR_FILE}: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    return 1;
  }
  const changes = steps.filter((step) => step.apply !== null);

  for (const step of steps) {
    process.stdout.write(`mdlineage: ${step.describe}\n`);
  }
  if (changes.length === 0) {
    process.stdout.write('mdlineage: nothing to do, already initialized\n');
    return 0;
  }
  if (values.write !== true) {
    process.stdout.write(
      `mdlineage: dry run, nothing written (${changes.length} change${changes.length === 1 ? '' : 's'}; pass --write to apply)\n`,
    );
    return 0;
  }

  // A step that cannot write reports the path and the reason, and the run fails
  // with 1 — a bootstrap that hit EACCES must not look like a clean one, and the
  // stack trace a leaked exception would print says nothing a user can act on.
  for (const step of changes) {
    if (!step.apply) continue;
    try {
      process.stdout.write(`mdlineage: ${step.apply()}\n`);
    } catch (error) {
      process.stderr.write(
        `mdlineage: cannot write ${step.target}: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      return 1;
    }
  }
  return 0;
}
