/**
 * `mdlineage init`: bootstrap a repository (§10.1).
 *
 * Generates the config, the `.gitattributes` line-ending policy and the empty
 * schema directory. The default is a dry run: nothing is written until
 * `--write` is passed, matching the project's "writing is explicit" decision.
 * An existing `.gitattributes` is only ever appended to, never rewritten.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'node:fs';
import { cwd as processCwd } from 'node:process';
import { resolve, join } from 'node:path';
import { repositoryRoot } from './git.js';

const CONFIG_FILE = 'mdlineage.config.yaml';
const ATTR_FILE = '.gitattributes';
const SCHEMA_DIR = 'schemas';

const ATTR_POLICY = '* text=auto eol=lf';

const CONFIG_CONTENT = `# MDLineage configuration (generated by \`mdlineage init\`).
configVersion: 1
metadata:
  # Gradual adoption: documents without metadata are warnings, not errors.
  # Set this to true once the corpus is fully onboarded.
  required: false
`;

interface Step {
  /** Filesystem action to take, or null when there is nothing to do. */
  apply: (() => string) | null;
  /** One-line report of what this step does (or already did). */
  describe: string;
}

/** Plan the init steps for `root` without touching the filesystem. */
function plan(root: string): Step[] {
  const steps: Step[] = [];

  const configPath = join(root, CONFIG_FILE);
  if (existsSync(configPath)) {
    steps.push({ apply: null, describe: `${CONFIG_FILE}: already present, left unchanged` });
  } else {
    steps.push({
      apply: () => `created ${CONFIG_FILE}`,
      describe: `create ${CONFIG_FILE} (metadata.required: false)`,
    });
  }

  const attrPath = join(root, ATTR_FILE);
  if (!existsSync(attrPath)) {
    steps.push({
      apply: () => `created ${ATTR_FILE}`,
      describe: `create ${ATTR_FILE}:`,
    });
    steps.push({ apply: null, describe: `+${ATTR_POLICY}` });
  } else {
    const existing = readFileSync(attrPath, 'utf8');
    const lines = new Set(
      existing
        .split('\n')
        .map((line) => line.trimEnd())
        .filter((line) => line.length > 0),
    );
    if (lines.has(ATTR_POLICY)) {
      steps.push({ apply: null, describe: `${ATTR_FILE}: already present, left unchanged` });
    } else {
      steps.push({
        apply: () => `appended to ${ATTR_FILE}`,
        describe: `append to ${ATTR_FILE}:`,
      });
      steps.push({ apply: null, describe: `+${ATTR_POLICY}` });
    }
  }

  const schemaPath = join(root, SCHEMA_DIR);
  if (existsSync(schemaPath)) {
    steps.push({ apply: null, describe: `${SCHEMA_DIR}/: already present, left unchanged` });
  } else {
    steps.push({
      apply: () => `created ${SCHEMA_DIR}/`,
      describe: `create ${SCHEMA_DIR}/ (empty schema directory)`,
    });
  }

  return steps;
}

/** `mdlineage init`: print the plan; only `--write` touches the filesystem. */
export function runInit(args: string[], values: { write?: boolean; config?: string }): number {
  const stray = args.filter((arg) => arg.startsWith('-'));
  if (stray.length > 0) {
    process.stderr.write(`mdlineage: unknown option: ${stray.join(', ')}\n\n`);
    return 2;
  }
  if (values.config) {
    process.stderr.write(`mdlineage: init does not take --config\n`);
    return 2;
  }

  const cwd = processCwd();
  // The bootstrap is a repository-level contract; fall back to the CWD when
  // there is no git repository to anchor at.
  const root = repositoryRoot(cwd) ?? resolve(cwd);

  const steps = plan(root);
  const changes = steps.filter((step) => step.apply !== null);

  for (const step of steps) {
    process.stdout.write(`mdlineage: ${step.describe}\n`);
  }
  if (changes.length === 0) {
    process.stdout.write('mdlineage: nothing to do, already initialized\n');
    return 0;
  }
  if (values.write !== true) {
    process.stdout.write(
      `mdlineage: dry run, nothing written (${changes.length} change${changes.length === 1 ? '' : 's'}; pass --write to apply)\n`,
    );
    return 0;
  }

  const configPath = join(root, CONFIG_FILE);
  if (!existsSync(configPath)) writeFileSync(configPath, CONFIG_CONTENT);

  const attrPath = join(root, ATTR_FILE);
  if (!existsSync(attrPath)) {
    writeFileSync(attrPath, `${ATTR_POLICY}\n`);
  } else {
    const existing = readFileSync(attrPath, 'utf8');
    const lines = new Set(
      existing
        .split('\n')
        .map((line) => line.trimEnd())
        .filter((line) => line.length > 0),
    );
    if (!lines.has(ATTR_POLICY)) appendFileSync(attrPath, `${ATTR_POLICY}\n`);
  }

  const schemaPath = join(root, SCHEMA_DIR);
  if (!existsSync(schemaPath)) mkdirSync(schemaPath, { recursive: true });

  for (const step of changes) {
    if (step.apply) process.stdout.write(`mdlineage: ${step.apply()}\n`);
  }
  return 0;
}
